given_name = input("Given name:")
family_name = input("Family name:")
street_add = input ("Street address:")
postal = input("City and postal code:")
print(given_name +" "+ family_name)
print(street_add)
print(postal)